#!/usr/bin/env python
# _*_ coding:utf-8 _*_

#高阶函数
def add(x, y, f):
    return f(x) + f(y)

print(add(-5, 6, abs))

#map
def f(x):
    return x*x

r=map(f,[1,2,3,4,5,6,7,8,9])
print(list(r))

#reduce  把序列[1, 3, 5, 7, 9]变换成整数13579

from functools import reduce
def fn(x, y):
    return x * 10 + y
r=reduce(fn, [1, 3, 5, 7, 9])
print(r)




